/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import uk.ac.kcl.dsl.ui.AbstractSql_dslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Sql_dslUiModule extends AbstractSql_dslUiModule {
  public Sql_dslUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe type Sql_dslUiModule is already defined in Sql_dslUiModule.java.");
  }
}
