/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.dsl.sql_dsl.AvgFunction;
import uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Avg Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AvgFunctionImpl extends FunctionsImpl implements AvgFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AvgFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Sql_dslPackage.Literals.AVG_FUNCTION;
  }

} //AvgFunctionImpl
