/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.dsl.sql_dsl.FromAndWhereClauses;
import uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage;
import uk.ac.kcl.dsl.sql_dsl.TableName;
import uk.ac.kcl.dsl.sql_dsl.WhereDec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>From And Where Clauses</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.impl.FromAndWhereClausesImpl#getTable <em>Table</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.impl.FromAndWhereClausesImpl#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FromAndWhereClausesImpl extends MinimalEObjectImpl.Container implements FromAndWhereClauses
{
  /**
   * The cached value of the '{@link #getTable() <em>Table</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTable()
   * @generated
   * @ordered
   */
  protected EList<TableName> table;

  /**
   * The cached value of the '{@link #getZ() <em>Z</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZ()
   * @generated
   * @ordered
   */
  protected EList<WhereDec> z;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FromAndWhereClausesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Sql_dslPackage.Literals.FROM_AND_WHERE_CLAUSES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TableName> getTable()
  {
    if (table == null)
    {
      table = new EObjectResolvingEList<TableName>(TableName.class, this, Sql_dslPackage.FROM_AND_WHERE_CLAUSES__TABLE);
    }
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WhereDec> getZ()
  {
    if (z == null)
    {
      z = new EObjectContainmentEList<WhereDec>(WhereDec.class, this, Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z);
    }
    return z;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return ((InternalEList<?>)getZ()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        return getTable();
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return getZ();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        getTable().clear();
        getTable().addAll((Collection<? extends TableName>)newValue);
        return;
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z:
        getZ().clear();
        getZ().addAll((Collection<? extends WhereDec>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        getTable().clear();
        return;
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z:
        getZ().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        return table != null && !table.isEmpty();
      case Sql_dslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return z != null && !z.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FromAndWhereClausesImpl
