/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.dsl.sql_dsl.MinFunction;
import uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Min Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MinFunctionImpl extends FunctionsImpl implements MinFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MinFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Sql_dslPackage.Literals.MIN_FUNCTION;
  }

} //MinFunctionImpl
