/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage;
import uk.ac.kcl.dsl.sql_dsl.SumFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sum Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SumFunctionImpl extends FunctionsImpl implements SumFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SumFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Sql_dslPackage.Literals.SUM_FUNCTION;
  }

} //SumFunctionImpl
