/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alter Table Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.AlterTableStatement#getTable <em>Table</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.AlterTableStatement#getAddDropUpdate <em>Add Drop Update</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getAlterTableStatement()
 * @model
 * @generated
 */
public interface AlterTableStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.dsl.sql_dsl.TableName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference list.
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getAlterTableStatement_Table()
   * @model
   * @generated
   */
  EList<TableName> getTable();

  /**
   * Returns the value of the '<em><b>Add Drop Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Drop Update</em>' containment reference.
   * @see #setAddDropUpdate(EObject)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getAlterTableStatement_AddDropUpdate()
   * @model containment="true"
   * @generated
   */
  EObject getAddDropUpdate();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.AlterTableStatement#getAddDropUpdate <em>Add Drop Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add Drop Update</em>' containment reference.
   * @see #getAddDropUpdate()
   * @generated
   */
  void setAddDropUpdate(EObject value);

} // AlterTableStatement
