/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#getType <em>Type</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#isNotNull <em>Not Null</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getColumnDeclaration()
 * @model
 * @generated
 */
public interface ColumnDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getColumnDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.dsl.sql_dsl.DataStructureType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see uk.ac.kcl.dsl.sql_dsl.DataStructureType
   * @see #setType(DataStructureType)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getColumnDeclaration_Type()
   * @model
   * @generated
   */
  DataStructureType getType();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see uk.ac.kcl.dsl.sql_dsl.DataStructureType
   * @see #getType()
   * @generated
   */
  void setType(DataStructureType value);

  /**
   * Returns the value of the '<em><b>Not Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not Null</em>' attribute.
   * @see #setNotNull(boolean)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getColumnDeclaration_NotNull()
   * @model
   * @generated
   */
  boolean isNotNull();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration#isNotNull <em>Not Null</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not Null</em>' attribute.
   * @see #isNotNull()
   * @generated
   */
  void setNotNull(boolean value);

} // ColumnDeclaration
