/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreign Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ForeignKey#getColumnAsFK <em>Column As FK</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ForeignKey#getForeignTable <em>Foreign Table</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.ForeignKey#getForeignColumns <em>Foreign Columns</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getForeignKey()
 * @model
 * @generated
 */
public interface ForeignKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Column As FK</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column As FK</em>' reference list.
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getForeignKey_ColumnAsFK()
   * @model
   * @generated
   */
  EList<ColumnDeclaration> getColumnAsFK();

  /**
   * Returns the value of the '<em><b>Foreign Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Table</em>' reference.
   * @see #setForeignTable(TableDeclaration)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getForeignKey_ForeignTable()
   * @model
   * @generated
   */
  TableDeclaration getForeignTable();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.ForeignKey#getForeignTable <em>Foreign Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreign Table</em>' reference.
   * @see #getForeignTable()
   * @generated
   */
  void setForeignTable(TableDeclaration value);

  /**
   * Returns the value of the '<em><b>Foreign Columns</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.dsl.sql_dsl.ColumnDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Columns</em>' reference list.
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getForeignKey_ForeignColumns()
   * @model
   * @generated
   */
  EList<ColumnDeclaration> getForeignColumns();

} // ForeignKey
