/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.Functions#getColumn <em>Column</em>}</li>
 *   <li>{@link uk.ac.kcl.dsl.sql_dsl.Functions#getX <em>X</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getFunctions()
 * @model
 * @generated
 */
public interface Functions extends Statement
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.dsl.sql_dsl.CD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' reference list.
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getFunctions_Column()
   * @model
   * @generated
   */
  EList<CD> getColumn();

  /**
   * Returns the value of the '<em><b>X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' containment reference.
   * @see #setX(FromAndWhereClauses)
   * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getFunctions_X()
   * @model containment="true"
   * @generated
   */
  FromAndWhereClauses getX();

  /**
   * Sets the value of the '{@link uk.ac.kcl.dsl.sql_dsl.Functions#getX <em>X</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' containment reference.
   * @see #getX()
   * @generated
   */
  void setX(FromAndWhereClauses value);

} // Functions
