/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Min Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getMinFunction()
 * @model
 * @generated
 */
public interface MinFunction extends Functions
{
} // MinFunction
