/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.sql_dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.dsl.sql_dsl.Sql_dslPackage#getSumFunction()
 * @model
 * @generated
 */
public interface SumFunction extends Functions
{
} // SumFunction
