/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.dsl.Sql_dslRuntimeModule;
import uk.ac.kcl.dsl.Sql_dslStandaloneSetup;
import uk.ac.kcl.dsl.ide.Sql_dslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Sql_dslIdeSetup extends Sql_dslStandaloneSetup {
  @Override
  public Injector createInjector() {
    Sql_dslRuntimeModule _sql_dslRuntimeModule = new Sql_dslRuntimeModule();
    Sql_dslIdeModule _sql_dslIdeModule = new Sql_dslIdeModule();
    return Guice.createInjector(Modules2.mixin(_sql_dslRuntimeModule, _sql_dslIdeModule));
  }
}
