/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.dsl.ui.contentassist;

import uk.ac.kcl.dsl.ui.contentassist.AbstractSql_dslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Sql_dslProposalProvider extends AbstractSql_dslProposalProvider {
}
